### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by brettbeatty** [brett-test/repo#9]
The .repo-meta.yml file in this repository has the following invalid values:
**Database**:
- [x] Brett's Relational Database
- [ ] Some NoSQL Database

**Software**:
- [ ] Brett's Bogus Software
- [x] AI

**Service**:
- [ ] Google

**Server**:
- [ ] Mega On-Prem Server
- [ ] T2.Nano Instance
